version: '3.3'

services:
  postgres_service:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpasswd
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_store
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
